name: flutter_application_app_ranking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  geolocator: ^14.0.3
  http: ^1.6.0
  supabase_flutter: ^2.14.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.2.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fundo_pedra.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true # Remove a transparência no iOS e coloca fundo branco
  adaptive_icon_background: "#1F1F1F" # Cor de fundo no Android
  adaptive_icon_foreground: "assets/logo.png" # A logo por cima da cor no Android

flutter_native_splash:
  color: "#1F1F1F" # Dica: Coloquei a mesma cor escura do ícone pra combinar, mas mude para "#FFFFFF" se preferir fundo branco!
  image: assets/logo.png
  android_12:
    image: assets/logo.png